<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="CommunityToolkit.Labs.WinUI.Controls.MarkdownTextBlock" Version="0.1.251002-build.2316" />
    <PackageVersion Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.250402" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.250402" />
    <PackageVersion Include="DynamicData" Version="9.4.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tasks" Version="9.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="Microsoft.Extensions.AI.AzureAIInference" Version="9.9.1-preview.1.25474.6" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="Microsoft.Extensions.Logging.EventLog" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.Onnx" Version="1.57.0-alpha" />
    <PackageVersion Include="OllamaSharp" Version="5.4.7" />
    <PackageVersion Include="ReactiveUI" Version="22.0.1" />
    <PackageVersion Include="ReactiveUI.SourceGenerators" Version="2.4.1" />
    <PackageVersion Include="ReactiveUI.WinUI" Version="22.0.1" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.14.0" />
    <PackageVersion Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="9.9.1" />
    <PackageVersion Include="Microsoft.Extensions.AI.Ollama" Version="9.5.0-preview.1.25265.7" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="9.3.0-preview.1.25161.3" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.250402" />
    <PackageVersion Include="CommunityToolkit.WinUI.Extensions" Version="8.2.250402" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-rc.1.25451.107" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.6584" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.0.250930001-experimental1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="System.Interactive" Version="6.0.3" />
    <PackageVersion Include="System.Interactive.Async" Version="6.0.3" />
    <PackageVersion Include="System.Reactive" Version="6.0.1" />
    <PackageVersion Include="xunit.v3" Version="2.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
</Project>