// <auto-generated />
using System;
using BigChat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigChat.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251011143503_RemovesEmbbedingTables")]
    partial class RemovesEmbbedingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("NVarChar(255)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVarChar(255)");

                    b.Property<string>("ThinkContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Message", b =>
                {
                    b.HasOne("BigChat.Infrastructure.Data.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
