// <auto-generated />
using System;
using BigChat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigChat.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("NVarChar(255)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.FileEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ContentsEmbedding")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("Blob");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<int>("UserFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserFileId");

                    b.ToTable("FileEmbeddings");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVarChar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.UserFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVarChar(255)");

                    b.HasKey("Id");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.FileEmbedding", b =>
                {
                    b.HasOne("BigChat.Infrastructure.Data.Models.UserFile", "UserFile")
                        .WithMany("FileEmbeddings")
                        .HasForeignKey("UserFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFile");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Message", b =>
                {
                    b.HasOne("BigChat.Infrastructure.Data.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BigChat.Infrastructure.Data.Models.UserFile", b =>
                {
                    b.Navigation("FileEmbeddings");
                });
#pragma warning restore 612, 618
        }
    }
}
